### ISSUE TITLE
这个不能直接在termux中运行嘛？

### ISSUE THREAD

**Issue by xp12047** [ahui2016/mima#1]
![Screenshot_20220517_090707_com termux](https://user-images.githubusercontent.com/56335408/168706768-7701449f-51a1-4535-8240-b5c9e447b230.jpg)
![Screenshot_20220517_090702_com termux](https://user-images.githubusercontent.com/56335408/168706777-48937ec2-532b-44fc-9cd5-8838bd2b0ca9.jpg)
不好意思，我对go和linux都不了解。但我之前一直想找个密码管理的能在termux中运行的。我才发现你这个最合适。我下载linux那个然后不知道该怎么让它运行起来。。termux里面有go的环境了。

**Comment by ahui2016** [comment]
你先用 `chmod +x mima` 把 mima 设为可执行文件，用命令 `./mima` 试试看。

如果不行，可能就要在 termux 编译了，你试试用 `git clone https://github.com/ahui2016/mima.git` 下载源码，如果没有 git, 可以到这里 <https://github.com/ahui2016/mima/releases/tag/2022-03-03> 下载 source code, 解压缩后放进 termux, 进文件夹内执行 `go build` 即可编译出一个 mima 文件。

**Comment by xp12047** [comment]
![Screenshot_20220517_164455_com termux](https://user-images.githubusercontent.com/56335408/168769885-0e131848-abc4-437c-a77b-5f64b2057585.jpg)
谢谢，git 不行，我直接下载解压好了也build了，但是好像还是不行，不知道我这个运行方式对不？

**Comment by xp12047** [comment]
![Screenshot_20220517_165558_com termux](https://user-images.githubusercontent.com/56335408/168772067-d6f042f1-895e-4328-9200-cebcb22805a0.jpg)
还有办法解决嘛

**Comment by xp12047** [comment]
![Screenshot_20220517_170441_com termux](https://user-images.githubusercontent.com/56335408/168774337-6b2f0e2d-748a-4fad-a702-f07d1b093e7f.jpg)
![Screenshot_20220517_170437_com android chrome](https://user-images.githubusercontent.com/56335408/168774344-fe903b5a-fb06-4544-811e-333c836faf18.jpg)
可以了，谢谢谢！我还有个疑问，我termux没有安装sql不要紧吧，但是它的确运行成功了呢😄

**Comment by xp12047** [comment]
> 哈哈哈，你用一下看看，能用就行。如果你是直接下载的 mima, 而不是自己用源码编译的话，那么那个 mima 文件里面就已经包含了一切（这就是 Go 语言的一个大优点，可以打包成这种一个文件直接启动的单文件程序）。
明白，谢谢😊，你开发的工具都很棒！我还有个问题，就是这个chmod +x mima命令哪里可以找相关的使用说明，我不懂。windows上也是这样操作嘛，chmod不是按键吧，是要输入的命令嘛

**Comment by xp12047** [comment]
> > 哈哈哈，你用一下看看，能用就行。如果你是直接下载的 mima, 而不是自己用源码编译的话，那么那个 mima 文件里面就已经包含了一切（这就是 Go 语言的一个大优点，可以打包成这种一个文件直接启动的单文件程序）。
> > 明白，谢谢😊，你开发的工具都很棒！我挺喜的

对了，它的数据保存在哪个文件夹了？我没有指定它

**Comment by ahui2016** [comment]
上面你的截图里， [database] 后面就是。

**Comment by xp12047** [comment]
> 你的截图里，[数据库] 后面就是。

额😓，我是真的愚蠢。谢谢😜

**Comment by xp12047** [comment]
如果升级的话，我该？

**Comment by ahui2016** [comment]
直接下载一个新的 mima, 覆盖旧的就行。

**Comment by xp12047** [comment]
> 直接下载一个新的 mima, 覆盖旧的就行。

额...谢谢
